[tools]
argocd = "latest"
cosign = "latest"
gh = "latest"
go = "latest"
helm = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "latest"
terraform = "latest"
tflint = "latest"
trivy = "latest"
